name: 3GPISN
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz
  - astropy
  - h5py
  - jupyterlab
  - lalsuite
  - matplotlib
  - numpy
  - pip
  - pystan
  - python=3.7
  - scipy
  - seaborn
  - tqdm
